"""empty message

Revision ID: 29656a503df2
Revises: 1dd60ac3cf36
Create Date: 2020-02-20 18:06:17.598932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29656a503df2'
down_revision = '1dd60ac3cf36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('salary', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
