"""empty message

Revision ID: 32016499c876
Revises: 
Create Date: 2020-02-17 19:25:57.113743

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32016499c876'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    op.add_column('players', sa.Column('agent', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('players', 'agent')
    op.create_table('stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batting_avg', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('on_base', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('strikeouts', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('walks', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('player_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], name='stats_player_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stats_pkey')
    )
    # ### end Alembic commands ###
