"""empty message

Revision ID: 70e4df4b4f4c
Revises: 842a26650a2a
Create Date: 2020-03-02 20:58:41.596116

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '70e4df4b4f4c'
down_revision = '842a26650a2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('total_payroll', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'total_payroll')
    # ### end Alembic commands ###
