"""empty message

Revision ID: 842a26650a2a
Revises: 
Create Date: 2020-03-02 20:37:58.115375

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '842a26650a2a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agents', sa.Column('salary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agents', 'salary')
    # ### end Alembic commands ###
